### ISSUE TITLE
Onde está o codigo para o app scritp?

### ISSUE THREAD

**Issue by tems** [heraclitothiago/links#1]
Oi Fernando, parabpens pelo projeto!!

Já morei dois anos em Codó, de 2006 a 2008, assumi na CAixa aí. Tenho ótimas lembranças.
Cara não localizei o código para o app script.
Também tenho outra profissão (contador, bancário) mas a Tenologia está nas veias!!!

Aguardo retorno,
tomazems@gmail.com

**Comment by heraclitothiago** [comment]
Ola. Muito obrigado pelo Feedback.

O código do app script está na íntegra no link https://www.tabnews.com.br/heraclitothiago/como-eu-criei-meu-proprio-linktree-com-googlesheets-no-banco-de-dados
Se trata do primeiro bloco de código que tem alguns comentários.
Qualquer duvida pode me contatar novamente.

Em 29 de mar. de 2024, à(s) 12:56, Tomaz Edson ***@***.***> escreveu:

﻿

Oi Fernando, parabpens pelo projeto!!

Já morei dois anos em Codó, de 2006 a 2008, assumi na CAixa aí. Tenho ótimas lembranças.
Cara não localizei o código para o app script.
Também tenho outra profissão (contador, bancário) mas a Tenologia está nas veias!!!

Aguardo retorno,
***@***.******@***.***>
